#!/bin/bash
# Node Settings
#########################setting####################
env=online
port=8001
uid=www.acgo.club
appPath=/home/finance/App/$uid
logPath=/home/finance/Logs/$uid
#########################env setting####################
export NODE_ENV=$env
export NODE_PORT=$port
export APP_PATH=$appPath
export LOG_PATH=$logPath
#########################starting####################
start() {
  echo start begin
    su -p website -c "pm2 start $appPath/bin/www -n $uid -l $logPath/log.log -e $logPath/error.log"
  echo start end
}
#########################status####################
status(){
  echo status begin
    su - website -c "pm2 show $uid"
  echo status end
}
#########################stoping####################
stop() {
  echo stop begin
    su - website -c "pm2 stop $uid"
  echo stop end
}
#########################restart####################
restart(){
  echo restart begin
    stop
    start
  echo restart end
}

case "$1" in
  start)
        start
        ;;
  status)
        status
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  ?|help)
        echo $"Usage: $0 {start|status|stop|restart|help|?}"
        ;;
  *)
        echo $"Usage: $0 {help|?}"
esac