//合集状态
exports.status={
    '1':'正常',
    '-1':'禁用'
}
//剧集类型
exports.type={
    '1':'B站',
    '2':'D站'
}
//剧集类型说明
exports.typeTip={
    '1':{
        'task':'http://bangumi.bilibili.com/anime/5523',
        'item':'http://bangumi.bilibili.com/anime/v/96644,http://www.bilibili.com/video/av8028645/,http://bangumi.bilibili.com/anime/5832/play#100381'
    },
    '2':{
        'task':'http://www.dilidili.com/anime/selector/,http://www.dilidili.wang/anime/selector/',
        'item':'http://www.dilidili.com/watch/9076/,http://www.dilidili.wang/watch/9076/'
    }
}
//合集任务状态
exports.taskStatus={
    '1':'正常',
    '0':'暂停',
    '-1':'停止'
}
//合集任务周期
exports.taskPeriod={
    '1':'周一',
    '2':'周二',
    '3':'周三',
    '4':'周四',
    '5':'周五',
    '6':'周六',
    '7':'周日'
}